FROM jenkins/jenkins:lts

USER root

# Instalar Docker + Node (opcional pero útil)
RUN apt update && \
    apt install -y docker.io curl

# Permisos docker
RUN usermod -aG docker jenkins

USER jenkins